#!/usr/bin/env bash

sudo -u docker docker run \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v ${HOME}/.azure:/root/.azure \
  -v ${HOME}/.docker:/root/.docker \
  azure-cli \
  az acr login \
    --name ${AZURE_CLI_NAME} \
    --subscription ${AZURE_CLI_SUBSCRIPTION}
